"""Default community resource categories and listings for bootstrap_site."""

DEFAULT_RESOURCE_CATEGORIES = [
    {
        'slug': 'healthcare',
        'name': 'Healthcare & Mental Health',
        'icon_class': 'fas fa-heartbeat',
        'ordering': 1,
    },
    {
        'slug': 'employment',
        'name': 'Jobs & Training',
        'icon_class': 'fas fa-briefcase',
        'ordering': 2,
    },
    {
        'slug': 'utilities',
        'name': 'Utilities & Transportation',
        'icon_class': 'fas fa-bolt',
        'ordering': 3,
    },
    {
        'slug': 'legal',
        'name': 'Legal & Financial Help',
        'icon_class': 'fas fa-balance-scale',
        'ordering': 4,
    },
    {
        'slug': 'additional',
        'name': 'Additional Community Resources',
        'icon_class': 'fas fa-info-circle',
        'ordering': 5,
    },
]

DEFAULT_RESOURCES = [
    # Healthcare
    {
        'category': 'healthcare',
        'name': 'Floyd County Health Department',
        'address': '1917 Bono Road, New Albany, IN 47150',
        'hours': 'Mon-Fri 8AM-4:30PM',
        'phone': '(812) 948-5435',
        'description': 'Primary care, immunizations, and health screenings on sliding scale fees.',
        'ordering': 1,
    },
    {
        'category': 'healthcare',
        'name': 'Clark County Health Department',
        'address': '1001 Missouri Ave, Jeffersonville, IN 47130',
        'hours': 'Mon-Fri 8AM-4:30PM',
        'phone': '(812) 283-5702',
        'description': 'Basic healthcare services, immunizations, and STD testing.',
        'ordering': 2,
    },
    {
        'category': 'healthcare',
        'name': 'LifeSpring Health Systems',
        'address': '460 Spring St, Jeffersonville, IN 47130',
        'phone': '(812) 284-8645',
        'website': 'https://www.lifespringhealthsystems.org/',
        'description': 'Mental health and substance abuse services with sliding scale fees.',
        'ordering': 3,
    },
    {
        'category': 'healthcare',
        'name': '988 Suicide & Crisis Lifeline',
        'phone': 'Call or text 988',
        'website': 'https://988indiana.org/',
        'description': '24/7 crisis support and mental health resources. Indiana-specific support available.',
        'ordering': 4,
    },
    {
        'category': 'healthcare',
        'name': 'Prescription Assistance',
        'phone': '1-800-503-6897',
        'website': 'https://www.needymeds.org',
        'description': 'Help finding affordable prescription medications.',
        'ordering': 5,
    },
    # Employment
    {
        'category': 'employment',
        'name': 'WorkOne Southern Indiana',
        'address': '319 Quartermaster Ct, Jeffersonville, IN 47130',
        'hours': 'Mon-Fri 8AM-5PM',
        'phone': '(812) 285-6442',
        'description': 'Job search assistance, resume help, and career counseling.',
        'ordering': 1,
    },
    {
        'category': 'employment',
        'name': 'Ivy Tech Community College - Southern Indiana',
        'address': '8204 Highway 311, Sellersburg, IN 47172',
        'phone': '(812) 246-3301',
        'description': 'Job training programs, workforce development, and continuing education.',
        'ordering': 2,
    },
    {
        'category': 'employment',
        'name': 'Indiana IMPACT Program',
        'phone': 'Contact local DFR office: (812) 285-6451',
        'website': 'https://www.in.gov/fssa/dfr/impact-job-training',
        'description': 'Job training and employment services for TANF recipients.',
        'ordering': 3,
    },
    {
        'category': 'employment',
        'name': 'Indiana Unemployment Benefits',
        'phone': '1-800-891-6499',
        'website': 'https://www.in.gov/dwd/unemployment-insurance/',
        'description': 'Financial assistance while searching for employment.',
        'ordering': 4,
    },
    # Utilities
    {
        'category': 'utilities',
        'name': 'Clark County CAP - Energy Assistance',
        'address': '1613 E 10th St, Jeffersonville, IN 47130',
        'hours': 'Mon-Fri 8AM-4:30PM',
        'phone': '(812) 283-4343',
        'description': 'LIHEAP energy assistance for heating and cooling bills.',
        'ordering': 1,
    },
    {
        'category': 'utilities',
        'name': 'Duke Energy - Customer Assistance',
        'phone': '1-800-521-2232',
        'website': 'https://www.duke-energy.com/home/billing/financial-assistance',
        'description': 'Low-income assistance programs and budget billing options.',
        'ordering': 2,
    },
    {
        'category': 'utilities',
        'name': 'TARC - Transit Authority',
        'phone': '(502) 585-1234',
        'website': 'https://ridetarc.org/',
        'description': 'Public transportation serving Louisville metro and Southern Indiana. Reduced fare programs available.',
        'ordering': 3,
    },
    {
        'category': 'utilities',
        'name': 'Indiana 211 Transportation',
        'phone': 'Dial 2-1-1',
        'website': 'https://in211.communityos.org/',
        'description': 'Information on local transportation resources and assistance programs.',
        'ordering': 4,
    },
    # Legal
    {
        'category': 'legal',
        'name': 'Indiana Legal Services - Southern Region',
        'address': '230 E. Main St, Corydon, IN 47112',
        'hours': 'Mon-Fri 9AM-5PM',
        'phone': '(812) 738-0077',
        'description': 'Free legal services for low-income individuals in civil matters.',
        'ordering': 1,
    },
    {
        'category': 'legal',
        'name': 'Consumer Credit Counseling Service',
        'phone': '(800) 355-2227',
        'website': 'https://www.cccsofamerica.org/',
        'description': 'Non-profit credit counseling and debt management services.',
        'ordering': 2,
    },
    {
        'category': 'legal',
        'name': 'VITA Tax Preparation',
        'address': 'Various locations during tax season',
        'phone': 'Contact IRS at 1-800-906-9887',
        'website': 'https://www.irs.gov/individuals/free-tax-return-preparation-for-qualifying-taxpayers',
        'description': 'Free tax preparation for low and moderate-income taxpayers.',
        'ordering': 3,
    },
    {
        'category': 'legal',
        'name': 'Money Smart Classes',
        'address': 'Local libraries and community centers',
        'phone': 'Contact Indiana 211 for locations',
        'description': 'Free financial literacy education and budget counseling.',
        'ordering': 4,
    },
    # Additional
    {
        'category': 'additional',
        'name': 'Childcare Assistance',
        'phone': '(812) 285-6451',
        'address': 'Clark County DFR Office',
        'description': 'CCDF childcare vouchers and assistance finding quality care.',
        'tags': 'childcare, family',
        'ordering': 1,
    },
    {
        'category': 'additional',
        'name': 'Adult Education',
        'phone': '(812) 285-6442',
        'address': 'WorkOne Southern Indiana',
        'description': 'GED classes and adult literacy programs through Ivy Tech.',
        'tags': 'education, GED',
        'ordering': 2,
    },
    {
        'category': 'additional',
        'name': 'Support Groups',
        'phone': '(812) 284-8645',
        'address': 'LifeSpring Health Systems',
        'description': 'AA, NA, grief support, and various recovery groups.',
        'tags': 'recovery, mental health',
        'ordering': 3,
    },
    {
        'category': 'additional',
        'name': 'Disability Services',
        'phone': '(812) 285-6442',
        'address': 'WorkOne - Vocational Rehabilitation',
        'description': 'Employment services and support for individuals with disabilities.',
        'tags': 'disability, employment',
        'ordering': 4,
    },
    {
        'category': 'additional',
        'name': 'Senior Services',
        'phone': '(812) 948-5435',
        'address': 'Floyd County Health Dept.',
        'description': 'Senior nutrition programs and wellness services.',
        'tags': 'seniors, nutrition',
        'ordering': 5,
    },
    {
        'category': 'additional',
        'name': 'United Way of Southern Indiana',
        'phone': '(812) 948-2273',
        'website': 'https://uwsiclark.org/',
        'description': 'Connects to various community resources and emergency assistance.',
        'tags': 'community, emergency',
        'ordering': 6,
    },
]
