# Generated by Django 4.2.7 on 2025-11-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Optional FontAwesome icon class', max_length=60)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('hours', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='frontend.resourcecategory')),
            ],
            options={
                'ordering': ['category__ordering', 'ordering', 'name'],
                'indexes': [models.Index(fields=['name'], name='frontend_re_name_38395b_idx'), models.Index(fields=['category', 'is_active'], name='frontend_re_categor_d9f623_idx')],
            },
        ),
    ]
