# Generated by Django 4.2.7 on 2026-06-30 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_event_date'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeffy_embed_html', models.TextField(blank=True, help_text='Paste the Zeffy embed code from your Zeffy dashboard.')),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('impact_25', models.CharField(default='Provides meals for 5 people', max_length=200)),
                ('impact_50', models.CharField(default='Supplies hygiene kits for 10 families', max_length=200)),
                ('impact_100', models.CharField(default='Provides emergency shelter for one night', max_length=200)),
            ],
            options={
                'verbose_name': 'Donation settings',
                'verbose_name_plural': 'Donation settings',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=5)),
                ('title', models.CharField(blank=True, help_text='Admin label / optional heading', max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Site content block',
                'verbose_name_plural': 'Site content blocks',
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=5)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='calendar_app.event')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
