# Generated by Django 4.2.7 on 2026-06-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_donationsettings_sitecontent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsettings',
            name='zeffy_form_link',
            field=models.URLField(default='https://www.zeffy.com/embed/donation-form/donate-to-change-lives-416?modal=true', help_text='Zeffy modal form URL used on donate buttons (zeffy-form-link).', max_length=500),
        ),
        migrations.AlterField(
            model_name='donationsettings',
            name='zeffy_embed_html',
            field=models.TextField(blank=True, help_text='Optional legacy iframe embed HTML from Zeffy dashboard.'),
        ),
    ]
