# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_seed_ui_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Optional background photo for the homepage hero. Leave blank to use the color gradient only.', null=True, upload_to='homepage/')),
                ('hero_use_gradient', models.BooleanField(default=True, help_text='Overlay the blue/red brand gradient on top of the hero photo.')),
            ],
            options={
                'verbose_name': 'Homepage settings',
                'verbose_name_plural': 'Homepage settings',
            },
        ),
    ]
